// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CallManagerAdaptor>>
abstract class CallManagerAdaptor implements RustOpaqueInterface {
  Future<void> call({
    required String ticket,
    required FutureOr<bool> Function(CallSessionAdaptor) onCallAccepted,
    required FutureOr<bool> Function() onCallRejected,
  });

  String getNodeAddress();

  static Future<CallManagerAdaptor> initialize({
    required String displayName,
    required FutureOr<bool> Function(String) onCallReceived,
    required FutureOr<bool> Function(CallSessionAdaptor) onCallAccepted,
  }) =>
      RustLib.instance.api.crateApiPhinyCoreAdaptorCallManagerAdaptorInitialize(
        displayName: displayName,
        onCallReceived: onCallReceived,
        onCallAccepted: onCallAccepted,
      );
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CallSessionAdaptor>>
abstract class CallSessionAdaptor implements RustOpaqueInterface {}
